services:
    marttiphpbb.topictemplate.listener:
        class: marttiphpbb\topictemplate\event\listener
        arguments:
            - @config_text
            - @dbal.conn
            - @request
            - @user
            - %tables.config_text%
            - %tables.forums%
        tags:
            - { name: event.listener }
