services:
    marttiphpbb.topictemplate.listener:
        class: marttiphpbb\topictemplate\event\listener
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@language'
            - '@marttiphpbb.topictemplate.service.store'
            - '%tables.forums%'
        tags:
            - { name: event.listener }

    marttiphpbb.topictemplate.posting_listener:
        class: marttiphpbb\topictemplate\event\listener
        arguments:
            - '@marttiphpbb.topictemplate.service.store'
        tags:
            - { name: event.listener }

    marttiphpbb.topictemplate.service.store:
        class: marttiphpbb\topictemplate\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'
